replicaCount: 2

currentValue: green

blueImage:
  repository: 7002370412/tumlog
  tag: "latest"  # Blue version of nginx

greenImage:
  repository: 7002370412/tumlog
  tag: "latest"  # Green version of nginx

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  type: NodePort
  port: 81

resources: {}

livenessProbe:
  httpGet:
    path: /health
    port: 81
readinessProbe:
  httpGet:
    path: /readiness
    port: 81

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
