apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment-{{ .Values.currentValue }}
  labels:
    app: my-app
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: "{{- if eq .Values.currentValue "blue" }}{{ .Values.blueImage.repository }}:{{ .Values.blueImage.tag }}{{ else }}{{ .Values.greenImage.repository }}:{{ .Values.greenImage.tag }}{{ end }}"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 81
          initialDelaySeconds: 10
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /readiness
            port: 81
          initialDelaySeconds: 10
          periodSeconds: 5
