apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: {{.Values.service.type }}
  ports:
    - port: {{.Values.service.port }}
      targetPort: 81
      nodePort: 30080
  selector:
    app: my-app
